//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class extRatingList
    {
        public System.Guid OlympVedId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<long> Place { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public string CryptNumber { get; set; }
    }
}
