//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympResults
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid OlympVedId { get; set; }
        public int TotalSum { get; set; }
        public int Place { get; set; }
    }
}
