//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OlympVseross2016Entities : DbContext
    {
        public OlympVseross2016Entities()
            : base("name=OlympVseross2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person_local> Person { get; set; }
        public virtual DbSet<PersonInOlympVed> PersonInOlympVed { get; set; }
        public virtual DbSet<PersonInOlympVedMark> PersonInOlympVedMark { get; set; }
        public virtual DbSet<OlympVed> OlympVed { get; set; }
        public virtual DbSet<Country_local> Country { get; set; }
        public virtual DbSet<DocumentType_local> DocumentType { get; set; }
        public virtual DbSet<Region_local> Region { get; set; }
        public virtual DbSet<SchoolClass_local> SchoolClass { get; set; }
        public virtual DbSet<Sex_local> Sex { get; set; }
        public virtual DbSet<extRatingList> extRatingList { get; set; }
        public virtual DbSet<DiplomaLevel> DiplomaLevel { get; set; }
        public virtual DbSet<OlympDiploma> OlympDiploma { get; set; }
        public virtual DbSet<OlympResults> OlympResults { get; set; }
    
        public virtual int RoleMember(string roleName, ObjectParameter result)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("roleName", roleName) :
                new ObjectParameter("roleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RoleMember", roleNameParameter, result);
        }
    }
}
