//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympDiploma
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public int OlympSubjectId { get; set; }
        public System.Guid OlympVedId { get; set; }
        public int SchoolClassId { get; set; }
        public int TotalSum { get; set; }
        public int Place { get; set; }
        public int DiplomaLevelId { get; set; }
        public string DiplomaRegNum { get; set; }
        public Nullable<System.DateTime> DiplomaDate { get; set; }
        public string BlankNumber { get; set; }
        public string CreateAuthor { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int OlympYear { get; set; }
    
        public virtual DiplomaLevel DiplomaLevel { get; set; }
        public virtual OlympVed OlympVed { get; set; }
        public virtual Person_local Person { get; set; }
        public virtual SchoolClass_local SchoolClass { get; set; }
    }
}
