//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlympVseross2016Entities : DbContext
    {
        public OlympVseross2016Entities()
            : base("name=OlympVseross2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person_local> Person { get; set; }
        public virtual DbSet<PersonInOlympVed> PersonInOlympVed { get; set; }
        public virtual DbSet<PersonInOlympVedMark> PersonInOlympVedMark { get; set; }
        public virtual DbSet<OlympVed> OlympVed { get; set; }
        public virtual DbSet<Country_local> Country { get; set; }
        public virtual DbSet<DocumentType_local> DocumentType { get; set; }
        public virtual DbSet<Region_local> Region { get; set; }
        public virtual DbSet<SchoolClass_local> SchoolClass { get; set; }
        public virtual DbSet<Sex_local> Sex { get; set; }
    }
}
