//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInOlympVedMark
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonInOlympVedId { get; set; }
        public int TaskNumber { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<decimal> AppealMark { get; set; }
    
        public virtual PersonInOlympVed PersonInOlympVed { get; set; }
    }
}
