//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_local
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person_local()
        {
            this.PersonInOlympVed = new HashSet<PersonInOlympVed>();
            this.OlympDiploma = new HashSet<OlympDiploma>();
        }
    
        public System.Guid Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int DocumentTypeId { get; set; }
        public string DocumentSeries { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentAuthor { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public int SchoolClassId { get; set; }
        public string SchoolName { get; set; }
        public int RegionId { get; set; }
        public int CountryId { get; set; }
        public int SexId { get; set; }
        public string City { get; set; }
    
        public virtual Country_local Country { get; set; }
        public virtual DocumentType_local DocumentType { get; set; }
        public virtual Region_local Region { get; set; }
        public virtual SchoolClass_local SchoolClass { get; set; }
        public virtual Sex_local Sex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonInOlympVed> PersonInOlympVed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OlympDiploma> OlympDiploma { get; set; }
    }
}
