//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInOlympVed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonInOlympVed()
        {
            this.PersonInOlympVedMark = new HashSet<PersonInOlympVedMark>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<System.Guid> OlympVedId { get; set; }
        public string CryptNumber { get; set; }
    
        public virtual OlympVed OlympVed { get; set; }
        public virtual Person_local Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonInOlympVedMark> PersonInOlympVedMark { get; set; }
    }
}
