//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> RegionNumber { get; set; }
        public string RodName { get; set; }
        public int PriemDictionaryId { get; set; }
        public string KladrCode { get; set; }
        public string RegionNumberStringValue { get; set; }
    }
}
