//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOlympDesctop
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public bool IsApproved { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string SID { get; set; }
        public string EmailTicket { get; set; }
        public string UILanguage { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
